-- MySQL Script generated by MySQL Workbench
-- Mon Dec 21 16:32:29 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema reporting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema reporting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reporting` DEFAULT CHARACTER SET utf8 ;
USE `reporting` ;

-- -----------------------------------------------------
-- Table `reporting`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reporting`.`projects` ;

CREATE TABLE IF NOT EXISTS `reporting`.`projects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `cost_center` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `project_id` VARCHAR(16) NULL DEFAULT NULL COMMENT '',
  `project_name` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `director` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT 'none@homedepot.com' COMMENT '',
  `status` VARCHAR(45) NULL DEFAULT 'pending' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC)  COMMENT '',
  UNIQUE INDEX `project_name_UNIQUE` (`project_name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 73
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `reporting`.`usage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reporting`.`usage` ;

CREATE TABLE IF NOT EXISTS `reporting`.`usage` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `usage_date` DATETIME NOT NULL COMMENT '',
  `cost` DOUBLE NOT NULL COMMENT '',
  `project_id` VARCHAR(16) NOT NULL COMMENT '',
  `resource_type` VARCHAR(128) NOT NULL COMMENT '',
  `account_id` VARCHAR(24) NOT NULL COMMENT '',
  `usage_value` DECIMAL(25,4) NOT NULL COMMENT '',
  `measurement_unit` VARCHAR(16) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2255
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `reporting`.`usage_export`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `reporting`.`usage_export` ;

CREATE TABLE IF NOT EXISTS `reporting`.`usage_export` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `report_date` DATETIME NULL DEFAULT NULL COMMENT '',
  `measurement_id` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `quantity` DECIMAL(50,4) NULL DEFAULT NULL COMMENT '',
  `measurement_unit` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `project_id` VARCHAR(20) NULL DEFAULT NULL COMMENT '',
  `location` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `resource_id` VARCHAR(128) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 296
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
